export const IMAGES = {
  SITE_PLACEHOLDER_1: '/images/placeholder.svg',
  HOME_HERO_1: '/images/home/home_hero.png',
  HOME_SECTION_IMAGE_1: '/images/home/home_about.png',
  HOME_BUTTON_LINKS_1: '/images/home/home_button_1.png',
  HOME_BUTTON_LINKS_2: '/images/home/home_button_2.png',
  HOME_BUTTON_LINKS_4: '/images/home/home_button_4.png',
  HOME_BUTTON_LINKS_5: '/images/home/home_button_1.png',
  HOME_BUTTON_LINKS_6: '/images/home/home_button_3.png',
  LOJA_HERO_1: '/images/placeholder.svg',
  EVENTOS_BANNER_1: '/images/placeholder.svg',
  PRODUTOS_DIGITAIS_PLACEHOLDER_1: '/images/placeholder.svg',
  PRODUTOS_DIGITAIS_HERO_1: '/images/placeholder.svg',
  AULA_DETAIL_PLACEHOLDER_1: '/images/placeholder.svg',
  STORE_IMAGE_FIELD_PREVIEW_1: '/images/placeholder.svg',
  AULAS_COVER_FALLBACK_1: '/images/placeholder.svg',
} as const
