export const TEXTS = {
  SITE_METADATA_TITLE_1: 'Denise Garcia',
  SITE_METADATA_DESCRIPTION_1:
    'Aulas de Pole Dance e artes sensuais, workshops, eventos e conteúdos de Denise Garcia.',
  SITE_HEADER_LOGO_1: 'Denise Garcia',
  SITE_AGE_GATE_TITLE_1: 'Você tem 18 anos ou mais?',
  SITE_AGE_GATE_DESCRIPTION_1: 'Alguns produtos desta página são destinados apenas a maiores de 18 anos.',
  SITE_AGE_GATE_CONFIRM_1: 'Sim, tenho 18 anos ou mais',
  SITE_AGE_GATE_REJECT_1: 'Não, voltar para o início',
  SITE_ADULT_GATE_TITLE_1: 'Conteúdo para maiores de 18 anos',
  SITE_ADULT_GATE_DESCRIPTION_1: 'Confirme sua idade para continuar.',
  SITE_ADULT_GATE_ACCEPT_1: 'Tenho 18 anos ou mais',
  SITE_ADULT_GATE_REJECT_1: 'Voltar para o início',
  SITE_ADMIN_MODAL_ERROR_FALLBACK_1: 'Não foi possível salvar as informações.',
  SITE_ADMIN_MODAL_SUCCESS_FALLBACK_1: 'Operação realizada com sucesso.',
  SITE_ADMIN_MODAL_CLOSE_1: 'Fechar',
  SITE_FOOTER_ADDRESS_LINE_1: 'Rua Rafael Citro, 42',
  SITE_FOOTER_ADDRESS_LINE_2: 'Jardim Rafael, Caçapava/SP',
  SITE_FOOTER_PHONE_1: '(12) 98815-3159',
  SITE_FOOTER_INSTAGRAM_HANDLE_1: '@denisegarcia.polestudio',
  SITE_FOOTER_INSTAGRAM_URL_1: 'https://www.instagram.com/denisegarcia.polestudio/',
  SITE_FOOTER_COPYRIGHT_1: '© Denise Garcia • Todos os direitos reservados',
  SITE_FOOTER_WHATSAPP_URL_1: 'https://wa.me/5512988153159',
  SITE_FOOTER_WHATSAPP_ARIA_1: 'Abrir WhatsApp',
  SITE_WHATSAPP_ITEM_TEMPLATE_1: 'Olá, quero comprar {title}.',
  STORE_IMAGE_FIELD_LABEL_1: 'Foto',
  STORE_IMAGE_FIELD_PREVIEW_LABEL_1: 'Preview',
  STORE_IMAGE_FIELD_EMPTY_1: 'Nenhuma imagem selecionada',
  STORE_IMAGE_FIELD_PREVIEW_ALT_1: 'Preview',
  STORE_DURATION_PINNED_LABEL_1: 'Publicação fixa',
  STORE_DURATION_DURATION_LABEL_1: 'Tempo de duração',
  STORE_CAROUSEL_DELETE_ARIA_1: 'Excluir publicação',
  STORE_CAROUSEL_DELETE_TITLE_1: 'Excluir publicação',
  STORE_CAROUSEL_DELETE_DESCRIPTION_1:
    'Tem certeza que deseja excluir esta imagem do carrossel?',
  STORE_CAROUSEL_DELETE_CONFIRM_1: 'Excluir',
  STORE_CAROUSEL_DELETE_CANCEL_1: 'Cancelar',
  STORE_CAROUSEL_FEED_LABEL_1: 'Feed',
  STORE_CAROUSEL_PREV_ARIA_1: 'Imagem anterior',
  STORE_CAROUSEL_NEXT_ARIA_1: 'Próxima imagem',
  STORE_CAROUSEL_GOTO_PREFIX_1: 'Ir para',
  STORE_UPLOAD_TITLE_1: 'Fotos dos produtos',
  STORE_UPLOAD_DESCRIPTION_1:
    'Faça upload de algumas imagens para mostrar o estilo e a qualidade dos produtos.',
  STORE_UPLOAD_EMPTY_1: 'Nenhuma foto selecionada ainda.',
  STORE_POST_FORM_HIDE_1: 'Ocultar',
  STORE_POST_FORM_SHOW_1: 'Mostrar',
  STORE_POST_FORM_HIDDEN_1: 'Formulário oculto.',
  HOME_BADGE_1: 'Studio',
  HOME_HERO_TITLE_1: 'Bem-vinda ao universo da Denise Garcia',
  HOME_HERO_DESCRIPTION_1:
    'Encontre aulas, workshops, eventos e produtos digitais com atendimento direto pelo WhatsApp.',
  HOME_BANNER_ACTION_1: 'Ver',
  HOME_ABOUT_TITLE_1: 'Sobre Denise Garcia',
  HOME_ABOUT_TEXT_1:
    'Professora e bailarina com foco em empoderamento feminino, expressão corporal e bem-estar. Experiências presenciais e online para todos os níveis.',
  HOME_SECTION_IMAGE_ALT_1: 'Sobre Denise',
  HOME_HERO_HEADLINE_1: 'Liberdade através da sensualidade',
  HOME_INTRO_TITLE_1: 'Olá, sou Denise Garcia',
  HOME_INTRO_TEXT_1:
    'Sou mentora de autoestima feminina, instrutora de Pole Dance e artes sensuais e graduada em Educação Física. Desde 2017, acompanho mulheres que desejam se movimentar, se expressar e construir uma relação mais confiante com o próprio corpo — cada uma no seu ritmo.',
  HOME_INTRO_IMAGE_ALT_1: 'Denise Garcia',
  HOME_HELP_TITLE_1: 'Encontre sua experiência',
  HOME_EXPERIENCES_TITLE_1: 'Experiências',
  HOME_EXPERIENCE_1_TITLE_1: 'Aulas personalizadas',
  HOME_EXPERIENCE_1_DESC_1:
    'Treinos presenciais e online com foco na sua evolução e segurança.',
  HOME_EXPERIENCE_2_TITLE_1: 'Workshops temáticos',
  HOME_EXPERIENCE_2_DESC_1:
    'Encontros intensivos para explorar técnicas, sensualidade e expressão.',
  HOME_LINK_AULAS_TITLE_1: 'Aulas',
  HOME_LINK_LOJA_TITLE_1: 'Loja',
  HOME_LINK_EVENTOS_TITLE_1: 'Eventos',
  HOME_LINK_WORKSHOPS_TITLE_1: 'Workshops',
  HOME_LINK_PRODUTOS_DIGITAIS_TITLE_1: 'Produtos digitais',
  LOJA_HERO_TITLE_1: 'Loja',
  LOJA_HERO_EYEBROW_1: 'Coleção',
  LOJA_SECTION_TITLE_1: 'Sobre a loja',
  LOJA_SECTION_P1_1:
    'Uma seleção de produtos para Pole Dance, sensualidade, bem-estar e autocuidado.',
  LOJA_SECTION_P2_1:
    'Compre por PIX, dinheiro ou cartão, com possibilidade de parcelamento. Enviamos para todo o Brasil. Se precisar de ajuda para escolher, fale com a Denise pelo WhatsApp.',
  LOJA_WHATSAPP_MESSAGE_1: 'Olá, quero saber mais sobre os produtos da Denise.',
  LOJA_WHATSAPP_BUTTON_1: 'Comprar pelo WhatsApp',
  LOJA_ADMIN_TITLE_1: 'Publicar no feed',
  LOJA_ADMIN_DESCRIPTION_1: 'Use a publicação fixa para manter o post sem prazo.',
  LOJA_ADMIN_SUCCESS_1: 'Publicação criada com sucesso.',
  LOJA_ADMIN_TRIGGER_1: '+ Adicionar',
  LOJA_ADMIN_LABEL_TITLE_1: 'Título',
  LOJA_ADMIN_PLACEHOLDER_TITLE_1: 'Título da publicação',
  LOJA_ADMIN_SUBMIT_1: 'Publicar',
  LOJA_ADMIN_ERROR_TITLE_1: 'Informe um título para a publicação.',
  LOJA_ADMIN_ERROR_EXPIRES_1: 'Defina uma data de duração ou marque como publicação fixa.',
  AULAS_PAGE_TITLE_1: 'Conheça as aulas',
  AULAS_BADGE_1: 'Aula',
  AULAS_DEFAULT_DESC_1: 'Você começa pelo seu nível, com orientação e evolução gradual.',
  AULAS_BUTTON_ONLINE_1: 'AGENDAR ONLINE',
  AULAS_BUTTON_PRESENTIAL_1: 'AGENDAR PRESENCIAL',
  AULAS_WHATSAPP_TEMPLATE_1: 'Olá, quero agendar a aula {title}.',
  AULAS_WHATSAPP_ONLINE_SUFFIX_1: 'Aula online',
  AULAS_WHATSAPP_PRESENTIAL_SUFFIX_1: 'Aula presencial',
  AULAS_WHATSAPP_REQUEST_1: 'Olá! Quero conhecer a aula de {title}. Pode me passar os horários e valores?',
  AULAS_WHATSAPP_MISSING_1: 'Configure o WhatsApp para contato',
  AULAS_CARD_BUTTON_1: 'Consultar horários e valores',
  AULAS_ADMIN_MODAL_TITLE_1: 'Adicionar aula',
  AULAS_ADMIN_MODAL_DESCRIPTION_1: 'Preencha as informações para publicar a aula.',
  AULAS_ADMIN_TITLE_LABEL_1: 'Título',
  AULAS_ADMIN_TITLE_PLACEHOLDER_1: 'Título da aula',
  AULAS_ADMIN_DESCRIPTION_LABEL_1: 'Descrição',
  AULAS_ADMIN_DESCRIPTION_PLACEHOLDER_1: 'Descrição da aula',
  AULAS_ADMIN_IMAGE_LABEL_1: 'Imagem',
  AULAS_ADMIN_PREVIEW_LABEL_1: 'Preview',
  AULAS_ADMIN_PREVIEW_EMPTY_1: 'Nenhuma imagem selecionada',
  AULAS_ADMIN_PREVIEW_ALT_1: 'Preview da aula',
  AULAS_ADMIN_SUBMIT_1: 'Salvar aula',
  AULAS_ADMIN_SAVING_1: 'Salvando...',
  AULAS_ADMIN_IMAGE_READING_1: 'Processando imagem...',
  AULAS_ADMIN_TRIGGER_1: '+ Adicionar nova aula',
  AULAS_ADMIN_ERROR_TITLE_1: 'Informe um título para a aula.',
  AULAS_ADMIN_ERROR_IMAGE_TYPE_1: 'Selecione uma imagem JPEG, PNG ou WebP.',
  AULAS_ADMIN_ERROR_IMAGE_SIZE_1: 'A imagem deve ter no máximo 2 MB.',
  AULAS_ADMIN_ERROR_IMAGE_DATA_1: 'Não foi possível processar a imagem selecionada. Escolha o arquivo novamente.',
  AULAS_ADMIN_ERROR_PERSISTENCE_1: 'Não foi possível salvar a aula. Tente novamente.',
  AULAS_EDIT_MODAL_TITLE_1: 'Editar aula',
  AULAS_EDIT_MODAL_DESCRIPTION_1: 'Atualize as informações da aula.',
  AULAS_EDIT_ICON_ARIA_1: 'Editar aula',
  AULAS_DELETE_ICON_ARIA_1: 'Excluir aula',
  AULAS_DELETE_TITLE_1: 'Excluir aula',
  AULAS_DELETE_DESCRIPTION_1: 'Tem certeza que deseja excluir {title}?',
  AULAS_DELETE_CONFIRM_1: 'Excluir',
  AULAS_DELETE_CANCEL_1: 'Cancelar',
  AULAS_DELETE_ERROR_1: 'Não foi possível excluir a aula.',
  AULA_DETAIL_DEFAULT_DESC_1: 'Conheça a proposta da aula e fale com a Denise para tirar suas dúvidas.',
  AULA_DETAIL_SECTION_ABOUT_TITLE_1: 'Sobre a aula',
  AULA_DETAIL_SECTION_HOW_TITLE_1: 'Como funciona',
  AULA_DETAIL_SECTION_INFO_TITLE_1: 'Informações adicionais',
  AULA_DETAIL_SECTION_HOW_TEXT_1:
    'Você começa com movimentos adequados ao seu nível e evolui aos poucos. As aulas incluem preparação do corpo e orientação técnica, respeitando seus limites e objetivos.',
  AULA_DETAIL_SECTION_INFO_TEXT_1:
    'Nunca fez antes? Tudo bem. Você não precisa chegar forte, flexível ou sabendo dançar. Fale com a Denise para consultar formatos, horários e valores.',
  AULA_DETAIL_HOTMART_LABEL_1: 'HOTMART',
  AULA_DETAIL_BUTTON_ONLINE_1: 'AGENDAR AULA ONLINE',
  AULA_DETAIL_BUTTON_PRESENTIAL_1: 'AGENDAR AULA PRESENCIAL',
  AULA_DETAIL_WHATSAPP_MISSING_1: 'Configure o WhatsApp em `.env` para ativar os botões.',
  WORKSHOPS_PAGE_TITLE_1: 'Workshops',
  WORKSHOPS_PAGE_DESCRIPTION_1:
    'Encontros com temas específicos para conhecer ou aprofundar técnicas, movimentos e formas de expressão.',
  WORKSHOPS_BADGE_1: 'Workshop',
  WORKSHOPS_WHATSAPP_TEMPLATE_1: 'Olá, quero informações sobre o workshop {title}.',
  WORKSHOPS_BUTTON_1: 'CONHECER O WORKSHOP',
  WORKSHOPS_ADMIN_MODAL_TITLE_1: 'Adicionar workshop',
  WORKSHOPS_ADMIN_MODAL_DESCRIPTION_1: 'Preencha os dados para publicar um novo workshop.',
  WORKSHOPS_ADMIN_TRIGGER_1: '+ Adicionar workshop',
  WORKSHOPS_ADMIN_TITLE_LABEL_1: 'Título',
  WORKSHOPS_ADMIN_TITLE_PLACEHOLDER_1: 'Nome do workshop',
  WORKSHOPS_ADMIN_DESCRIPTION_LABEL_1: 'Descrição',
  WORKSHOPS_ADMIN_DESCRIPTION_PLACEHOLDER_1: 'Detalhes do workshop',
  WORKSHOPS_ADMIN_SUBMIT_1: 'Salvar workshop',
  WORKSHOPS_ADMIN_SUBMIT_PENDING_1: 'Salvando...',
  WORKSHOPS_ADMIN_ERROR_TITLE_1: 'Informe um título para o workshop.',
  WORKSHOPS_ADMIN_ERROR_CREATE_1: 'Não foi possível criar o workshop. Tente novamente.',
  WORKSHOPS_EDIT_MODAL_TITLE_1: 'Editar workshop',
  WORKSHOPS_EDIT_MODAL_DESCRIPTION_1: 'Atualize os dados do workshop.',
  WORKSHOPS_EDIT_ICON_ARIA_1: 'Editar workshop',
  WORKSHOPS_EDIT_SUBMIT_1: 'Salvar alterações',
  WORKSHOPS_EDIT_ERROR_SLUG_1: 'Já existe um workshop com esse título.',
  WORKSHOPS_EDIT_ERROR_UPDATE_1: 'Não foi possível atualizar o workshop.',
  WORKSHOPS_DELETE_ICON_ARIA_1: 'Excluir workshop',
  WORKSHOPS_DELETE_TITLE_1: 'Excluir workshop',
  WORKSHOPS_DELETE_DESCRIPTION_1: 'Tem certeza que deseja excluir {title}?',
  WORKSHOPS_DELETE_CONFIRM_1: 'Excluir',
  WORKSHOPS_DELETE_PENDING_1: 'Excluindo...',
  WORKSHOPS_DELETE_CANCEL_1: 'Cancelar',
  WORKSHOPS_DELETE_ERROR_1: 'Não foi possível excluir o workshop.',
  EVENTOS_PAGE_TITLE_1: 'Eventos',
  EVENTOS_BANNER_ALT_1: 'Banner de eventos',
  EVENTOS_DESCRIPTION_1:
    'Encontros, apresentações e experiências para viver a dança e a sensualidade em boa companhia. Consulte a programação e os detalhes de cada evento.',
  EVENTOS_TYPES_TITLE_1: 'Tipos de eventos',
  EVENTOS_TYPE_1: 'Eventos corporativos',
  EVENTOS_TYPE_2: 'Aulas especiais para grupos',
  EVENTOS_TYPE_3: 'Experiências sensoriais',
  EVENTOS_TYPE_4: 'Apresentações e performances',
  EVENTOS_CONTACT_BUTTON_1: 'CONSULTAR PRÓXIMOS EVENTOS',
  EVENTOS_CONTACT_BUTTON_2: 'FALAR NO WHATSAPP',
  EVENTOS_WHATSAPP_MISSING_1: 'Configure o WhatsApp para contato',
  EVENTOS_SECTION_UPCOMING_1: 'Próximos eventos',
  EVENTOS_SECTION_P2_1:
    'Confira as próximas datas e reserve sua vaga direto pelo WhatsApp.',
  EVENTOS_CARD_BADGE_1: 'Evento presencial',
  EVENTOS_CARD_BUTTON_1: 'Ver detalhes do evento',
  EVENTOS_CARD_DESCRIPTION_FALLBACK_1: 'Fale com a Denise para conhecer a programação e saber como participar.',
  EVENTOS_NEXT_BADGE_1: 'Destaque da agenda',
  EVENTOS_EMPTY_TITLE_1: 'Novas datas em breve',
  EVENTOS_EMPTY_DESCRIPTION_1:
    'Ainda não há eventos publicados. Fale com a Denise pelo WhatsApp para acompanhar as próximas datas.',
  EVENTOS_WHATSAPP_ITEM_MESSAGE_1: 'Olá, quero informações sobre o evento {title}.',
  EVENTOS_ADMIN_MODAL_TITLE_1: 'Adicionar evento',
  EVENTOS_ADMIN_MODAL_DESCRIPTION_1: 'Preencha os dados para publicar o próximo evento.',
  EVENTOS_ADMIN_TITLE_LABEL_1: 'Título',
  EVENTOS_ADMIN_TITLE_PLACEHOLDER_1: 'Nome do evento',
  EVENTOS_ADMIN_DESCRIPTION_LABEL_1: 'Descrição',
  EVENTOS_ADMIN_DESCRIPTION_PLACEHOLDER_1: 'Detalhes rápidos do evento',
  EVENTOS_ADMIN_DATE_LABEL_1: 'Data do evento',
  EVENTOS_ADMIN_SUBMIT_1: 'Salvar evento',
  EVENTOS_ADMIN_TRIGGER_1: '+ Adicionar evento',
  EVENTOS_ADMIN_ERROR_TITLE_1: 'Informe um título para o evento.',
  EVENTOS_ADMIN_ERROR_SLUG_1: 'Já existe um evento com esse título. Ajuste para continuar.',
  EVENTOS_EDIT_MODAL_TITLE_1: 'Editar evento',
  EVENTOS_EDIT_MODAL_DESCRIPTION_1: 'Atualize os dados do evento.',
  EVENTOS_EDIT_MODAL_SUBMIT_1: 'Salvar alterações',
  EVENTOS_EDIT_ICON_ARIA_1: 'Editar evento',
  EVENTOS_DELETE_ICON_ARIA_1: 'Excluir evento',
  EVENTOS_DELETE_TITLE_1: 'Excluir evento',
  EVENTOS_DELETE_DESCRIPTION_1: 'Tem certeza que deseja excluir {title}?',
  EVENTOS_DELETE_CONFIRM_1: 'Excluir',
  EVENTOS_DELETE_CANCEL_1: 'Cancelar',
  EVENTOS_DELETE_ERROR_1: 'Não foi possível excluir o evento.',
  EVENTOS_DATE_FALLBACK_1: 'EM BREVE',
  EVENTOS_WHATSAPP_MESSAGE_1: 'Olá, quero informações sobre os próximos eventos.',
  PRODUTOS_DIGITAIS_PAGE_TITLE_1: 'Produtos digitais',
  PRODUTOS_DIGITAIS_DESCRIPTION_1:
    'E-books e aulas gravadas para acessar onde estiver e acompanhar no seu ritmo.',
  PRODUTOS_DIGITAIS_BUTTON_BUY_1: 'COMPRAR',
  PRODUTOS_DIGITAIS_WHATSAPP_MISSING_1: 'Configure o WhatsApp para comprar',
  PRODUTOS_DIGITAIS_HERO_TITLE_1: 'Produtos digitais',
  PRODUTOS_DIGITAIS_HERO_EYEBROW_1: 'Coleção',
  PRODUTOS_DIGITAIS_SECTION_TITLE_1: 'Sobre os produtos digitais',
  PRODUTOS_DIGITAIS_SECTION_P1_1:
    'E-books e aulas gravadas para aprofundar temas de técnica, movimento e expressão no seu ritmo.',
  PRODUTOS_DIGITAIS_SECTION_P2_1:
    'Abra o produto para conhecer o conteúdo, o formato e as informações de compra. Se tiver dúvidas, fale com a Denise pelo WhatsApp.',
  PRODUTOS_DIGITAIS_CARD_BUTTON_1: 'Conhecer o conteúdo',
  PRODUTOS_DIGITAIS_BADGE_EBOOK_1: 'E-book',
  PRODUTOS_DIGITAIS_BADGE_VIDEO_1: 'Aula digital',
  PRODUTOS_DIGITAIS_LINK_MISSING_1: 'Configurar link ou WhatsApp',
  PRODUTOS_DIGITAIS_WHATSAPP_MESSAGE_1:
    'Olá! Tenho interesse no produto digital {title}. Pode me passar os detalhes?',
  PRODUTOS_DIGITAIS_ADMIN_MODAL_TITLE_1: 'Adicionar produto digital',
  PRODUTOS_DIGITAIS_ADMIN_MODAL_DESCRIPTION_1:
    'Preencha os dados para publicar o produto digital.',
  PRODUTOS_DIGITAIS_ADMIN_TITLE_LABEL_1: 'Título',
  PRODUTOS_DIGITAIS_ADMIN_TITLE_PLACEHOLDER_1: 'Título do produto digital',
  PRODUTOS_DIGITAIS_ADMIN_DESCRIPTION_LABEL_1: 'Descrição',
  PRODUTOS_DIGITAIS_ADMIN_DESCRIPTION_PLACEHOLDER_1: 'Descrição do produto digital',
  PRODUTOS_DIGITAIS_ADMIN_LINK_LABEL_1: 'Link',
  PRODUTOS_DIGITAIS_ADMIN_LINK_PLACEHOLDER_1: 'https://',
  PRODUTOS_DIGITAIS_ADMIN_TYPE_LABEL_1: 'Tipo',
  PRODUTOS_DIGITAIS_ADMIN_TYPE_EBOOK_1: 'E-book',
  PRODUTOS_DIGITAIS_ADMIN_TYPE_VIDEO_1: 'Aula digital',
  PRODUTOS_DIGITAIS_ADMIN_SUBMIT_1: 'Salvar produto digital',
  PRODUTOS_DIGITAIS_ADMIN_TRIGGER_1: '+ ADICIONAR',
  PRODUTOS_DIGITAIS_ADMIN_ERROR_TITLE_1: 'Informe um título para o produto.',
  PRODUTOS_DIGITAIS_ADMIN_ERROR_TYPE_1: 'Selecione um tipo válido.',
  PRODUTOS_DIGITAIS_EDIT_MODAL_TITLE_1: 'Editar produto digital',
  PRODUTOS_DIGITAIS_EDIT_MODAL_DESCRIPTION_1: 'Atualize as informações do produto digital.',
  PRODUTOS_DIGITAIS_EDIT_ICON_ARIA_1: 'Editar produto digital',
  PRODUTOS_DIGITAIS_DELETE_ICON_ARIA_1: 'Excluir produto digital',
  PRODUTOS_DIGITAIS_DELETE_TITLE_1: 'Excluir produto digital',
  PRODUTOS_DIGITAIS_DELETE_DESCRIPTION_1: 'Tem certeza que deseja excluir {title}?',
  PRODUTOS_DIGITAIS_DELETE_CONFIRM_1: 'Excluir',
  PRODUTOS_DIGITAIS_DELETE_CANCEL_1: 'Cancelar',
  PRODUTOS_DIGITAIS_DELETE_ERROR_1: 'Não foi possível excluir o produto digital.',
  FORBIDDEN_TITLE_1: 'Acesso negado',
  FORBIDDEN_DESCRIPTION_1: 'Você não tem permissão para acessar essa área.',
  FORBIDDEN_BACK_HOME_1: 'Voltar para a Home',
} as const
